// let one = Number('1')
// console.log(typeof(one))
// console.log(Number("cat"))
// console.log(Number(''))
// console.log(Number(true))
// console.log(Number(false))
// console.log(parseInt("12"))
// console.log(parseInt("12.56"))
// console.log(parseInt("12oz"))
// console.log(parseInt("+12oz"))
// console.log(parseInt("10101",2))
// console.log(parseFloat("12 grams"))
// console.log(parseFloat("12.2 grams"))
// console.log(+"")
// console.log(+"1")
// console.log(+"2.3")
// console.log(+[])
// console.log(+"abc")

// let number = 42;
// console.log(number.toString())
// console.log((23).toString())
// console.log(23..toString())
// console.log(true.toString())
// console.log(false.toString())
// console.log([1,2,3].toString())
// console.log([1,undefined,2,null,3].toString())

// let obj = {a:"foo", b:"bar"}
// console.log(obj.toString())

console.log(String("hello"))
console.log(String("2"))
console.log(String("2.4"))
console.log(String("[1,2,3]"))
console.log(String({a: "foo", b:"bar"}))
console.log(String(null))
console.log(String(undefined))